package com.entity;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.id
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.userName
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.age
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.mobilePhone
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    private String mobilephone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.id
     *
     * @return the value of Person.id
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.id
     *
     * @param id the value for Person.id
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.userName
     *
     * @return the value of Person.userName
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.userName
     *
     * @param username the value for Person.userName
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.age
     *
     * @return the value of Person.age
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.age
     *
     * @param age the value for Person.age
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.mobilePhone
     *
     * @return the value of Person.mobilePhone
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.mobilePhone
     *
     * @param mobilephone the value for Person.mobilePhone
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }
}