package com.dao;

import com.entity.Person;
import com.entity.PersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    int countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Person
     *
     * @mbggenerated Tue Mar 24 16:35:10 CST 2020
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);
}